name: Build and Package Application
on: 
  push:
    branches:
      - master
      - main
jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        java-package: jdk

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build custom JRE with jlink
      shell: bash
      run: |
        $JAVA_HOME/bin/jlink --no-header-files --no-man-pages --add-modules ALL-MODULE-PATH --output jre

    - name: Copy resources to a separate directory
      shell: bash
      run: |
        mkdir resources
        cp -R src/main/resources/* resources/

    - name: Create Installer with jpackage
      shell: bash
      run: |
        $JAVA_HOME/bin/jpackage --name excelreformatter --input target --main-jar excelreformatter-1.0-SNAPSHOT.jar --main-class com.eyeshare.Dag.Main --runtime-image jre --type exe --icon src/main/logo/windows/logo.ico --resource-dir resources

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: installer-windows
        path: ./*.exe

  build_macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        java-package: jdk

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build custom JRE with jlink
      shell: bash
      run: |
        $JAVA_HOME/bin/jlink --no-header-files --no-man-pages --add-modules ALL-MODULE-PATH --output jre

    - name: Copy resources to a separate directory
      shell: bash
      run: |
        mkdir resources
        cp -R src/main/resources/* resources/

    - name: Create Installer with jpackage
      run: |
        $JAVA_HOME/bin/jpackage --name excelreformatter --input target --main-jar excelreformatter-1.0-SNAPSHOT.jar --main-class com.eyeshare.Dag.Main --type dmg --icon src/main/logo/macosx/logo.icn --resource-dir resources

    - name: Upload Installer
      uses: actions/upload-artifact@v2
      with:
        name: installer-macos
        path: ./*.dmg
